### PR TITLE
Clean up examples/ directory

### PR DESCRIPTION
**Pull request by ADITYADAS1999**
Clean up examples/ directory #573

### CODE REVIEW

**Comment by mattdangerw** [comment]
It would be nice to keep some sort of minimal content here...

```
# KerasNLP Examples

The `examples/` directly contains scripts built on top of the library that do not fit well into
the colab format used on [keras.io](https://keras.io/examples/). This includes recipes for
pre-training models and evaluating models on benchmarks such as GLUE.
```

We should do some light renaming of the content in this directory and fix all import after renaming.

 - Rename `/examples/bert/` -> `/examples/bert_pretraining/`
 - Delete the file `bert_finetune_glue.py` (we now have better code in the glue_finetuning directly).
 - Rename the file `bert_train.py` -> `bert_pretrain.py`.
 - Rename the file `bert_preprocess.py` -> `bert_create_pretraining_data.py`.

@chenmoneygithub do those renames look ok to you as well?

**Comment by ADITYADAS1999** [comment]
> It would be nice to keep some sort of minimal content in the README...
> 
> ```
> # KerasNLP Examples
> 
> The `examples/` directly contains scripts built on top of the library that do not fit well into
> the colab format used on [keras.io](https://keras.io/examples/). This includes recipes for
> pre-training models and evaluating models on benchmarks such as GLUE.
> ```


Thanks [mattdangerw](https://github.com/mattdangerw), I add this to readme 👍🏻

**Comment by ADITYADAS1999** [comment]
Hey @chenmoneygithub  can I make this changes, If those renames look ok ?


We should do some light renaming of the content in this directory and fix all import after renaming.


- Rename /examples/bert/ -> /examples/bert_pretraining/
- Delete the file bert_finetune_glue.py (we now have better code in the glue_finetuning directly).
- Rename the file bert_train.py -> bert_pretrain.py.
- Rename the file bert_preprocess.py -> bert_create_pretraining_data.py.

**Comment by mattdangerw** [comment]
@ADITYADAS1999 thanks! This looks good!

We will also need to update the README here -> https://github.com/keras-team/keras-nlp/blob/master/examples/bert/README.md to reflect the script renames. Should be a simpler find and replace.

Also can we delete this section entirely? https://github.com/keras-team/keras-nlp/blob/master/examples/bert/README.md#evaluating-bert-with-glue. We are removing the script on this PR.

**Comment by ADITYADAS1999** [comment]
> We will also need to update the README here -> https://github.com/keras-team/keras-nlp/blob/master/examples/bert/README.md to reflect the script renames. Should be a simpler find and replace.
> 

what kind of changes should I change here in the docs? can you suggest little bit.

**Comment by ADITYADAS1999** [comment]
> 
> Also can we delete this section entirely? https://github.com/keras-team/keras-nlp/blob/master/examples/bert/README.md#evaluating-bert-with-glue. We are removing the script on this PR.

In my opinion we have to remove this section, as we remove the  `bert_finetune_glue.py` file. kept this extra section generate confusion for new maintainers and contributors in future.

**Comment by mattdangerw** [comment]
@ADITYADAS1999

> can you suggest little bit.

Sure!

 - Let's delete this section -> https://github.com/keras-team/keras-nlp/blob/master/examples/bert/README.md#evaluating-bert-with-glue
 - Let's update the names of this scripts that have changed elsewhere in the README, for example ->
 
image

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999
> 
> > can you suggest little bit.
> 
> Sure!
> 
> * Let's delete this section -> https://github.com/keras-team/keras-nlp/blob/master/examples/bert/README.md#evaluating-bert-with-glue
> * Let's update the names of this scripts that have changed elsewhere in the README, for example ->
> 
> image

thanks [mattdangerw](https://github.com/mattdangerw)

**Review by mattdangerw — APPROVED** [review]
Thank you!

**Comment by ADITYADAS1999** [comment]
> Thank you!

Thanks [mattdangerw](https://github.com/mattdangerw) for reviewing 😀

**Pull request merged**
