### PR TITLE
Add `XLNetBackbone`

### PR DESCRIPTION
**Pull request by shivance**
Closes https://github.com/keras-team/keras-nlp/issues/753

Referring [XLNetBase](https://github.com/tensorflow/models/blob/v2.11.5/official/nlp/modeling/networks/xlnet_base.py#L415-L710), [TransformerXL](https://github.com/tensorflow/models/blob/v2.11.5/official/nlp/modeling/layers/transformer_xl.py#L322-L560), [Two stream Attention](https://github.com/tensorflow/models/blob/v2.11.3/official/nlp/modeling/layers/relative_attention.py)

### CODE REVIEW

**Comment by shivance** [comment]
Hi @mattdangerw, It's still a WIP, but would be obliged if you could take a look.
Thanks.

**Comment by shivance** [comment]
Still a WIP, working on fixing bugs and test failures.

**Comment by mattdangerw** [comment]
@shivance timely question! We actually have a contribution guide for models about to land here. https://github.com/keras-team/keras-nlp/pull/820

Could you try following that and give us feedback?

Re the overall stucture, lets keep everything in a `models/xlnet` directory for now (don't contribute directly to `keras_nlp.layers` just yet, though we can follow up with that), and while looking at huggingface or model garden for inspiration is totally fine, try to make sure we stick to the "local" style of KerasNLP wherever possible when writing layers, models etc.

We also should make sure we have the full forward pass matching correctly before we get too deep into review on style, etc. You can usually try making a colab for starters that aligns the forward pass with a reference implementation and share that here!

**Comment by shivance** [comment]
> @shivance, let me know when this is ready for review!

Really Sorry for slacking off here, am not able to find time cuz of personal reasons. Will follow up soon.

**Comment by abheesht17** [comment]
No hurry, take your time! Take care!

**Comment by susnato** [comment]
Hi @shivance can I please continue this PR?

**Comment by shivance** [comment]
@susnato I have done half of the work already, and the PR is bug prone, I'm not planning to work on it any sooner though as I've been onto #1052 . So you could probably fork my branch, and continue with my commits (which I made so far). What say?

**Comment by susnato** [comment]
Hi @shivance thanks for quick reply, I would love to continue your work. How about I fork your branch and push the commits on your repo(to shivance/keras-nlp_branch...) and you merge them, that way we both will share credits? or if you want I can copy the existing code and make a new PR. What do you say?

**Comment by shivance** [comment]
I think if I add you as collaborator on my fork, and then when you push to
my branch, the same PR should get updated without getting closed.

**Comment by susnato** [comment]
then please add me as  a collaborator @shivance .

**Comment by shivance** [comment]
@susnato just gave!

**Comment by susnato** [comment]
Hi @mattdangerw, I am currently working on this integration. I have one small doubt -  
As you said [here](https://github.com/keras-team/keras-nlp/pull/928#issuecomment-1487392967)
"We also should make sure we have the full forward pass matching correctly before we get too deep into review on style"
I am using the [HuggingFace Implementation and weights](https://huggingface.co/xlnet-base-cased) as a reference for forward pass since it is Tensorflow-2. Is it ok or should I switch to another implementation?

**Comment by susnato** [comment]
Hi @mattdangerw @abheesht17 , In [xlnet implementation](https://github.com/huggingface/transformers/blob/0b7b4429c78de68acaf72224eb6dae43616d820c/src/transformers/models/xlnet/modeling_tf_xlnet.py#L586) there are some optional arguments such as `mems` and `perm_mask` which are mostly used during pretraining but during inference we mostly leave it as `None`, but as in keras-nlp we don't define the call method for Backbones(as I noticed in all models), instead we define all the Input layers in `__init__` but that makes things complicated as if we define a Input layer for `mems`, we can't leave it `None`during the inference otherwise they will give error. 

Should I then define the call method in the backbone?(That would make this backbone an exception) or should I do a workaround(eg, instead of passing None we can pass -1e+9)?

**Comment by susnato** [comment]
Hi @shivance I am sorry but I think it's better to open a new PR. Since you created this PR I need to tag you all time to ask for changing description or asking reviews from maintainers, and also you might get bothered about getting tagged all the time, so I am making a new PR but please do not worry, I am going to continue from your commits.

**Pull request closed without merging**
