### PR TITLE
Update register_keras_serializable to use saving module

### PR DESCRIPTION
**Pull request by mattdangerw**

### CODE REVIEW

**Comment by jbischof** [comment]
Aren't there at least 10x more callsites for this method? Is this just a pilot?

**Comment by mattdangerw** [comment]
> Aren't there at least 10x more callsites for this method? Is this just a pilot?

There are not. I think you are thinking of before Francois' changes for API export landed.

https://github.com/keras-team/keras-nlp/pull/811/ and similar PRs

**Comment by mattdangerw** [comment]
@chenmoneygithub can we update our accelerator image to use the latest `requirements.txt` from the repo?

**Review by jbischof — APPROVED** [review]

**Pull request merged**
