### PR TITLE
Adding XXBackboneTPUTests

### LINKED ISSUE #838: Adding `XXBackboneTPUTests`
I observed that currently we have unit tests for TPU for `BertBackbone` and `WhisperBackbone` .

Are we planning to add TPUTests for other models too ? If yes, then please assign me the issue.

cc : @mattdangerw @chenmoneygithub

### PR DESCRIPTION
**Pull request by shivance**
This PR adds TPU Tests for backbones of following models
1. Albert
2. FNet
3. Roberta
4. GPT2
5. OPT
6. XLMRoberta

Closes #838

### CODE REVIEW

**Comment by chenmoneygithub** [comment]
@shivance Thanks for the PR! I will need to patch and run it on TPU for sanity check.

**Comment by chenmoneygithub** [comment]
@shivance  `FNetBackboneTPUTest.test_predict` failed with error msg: 
```
ValueError: Missing data for input "segment_ids". You passed a data dictionary with keys ['token_ids', 'padding_mask']. Expected the following keys: ['segment_ids', 'token_ids']
```

You may need to correct the input format, thanks!

**Comment by shivance** [comment]
My bad, fixed it @chenmoneygithub !

**Comment by chenmoneygithub** [comment]
All passed, thank you!

**Review by chenmoneygithub — APPROVED** [review]

**Pull request merged**
