### PR TITLE
Standalone functions for generate pre/post processing for OPT

### PR DESCRIPTION
**Pull request by mattdangerw**
This is simply mirroring changes in https://github.com/keras-team/keras-nlp/pull/998 for OPT, with the post-release plan still being to move most of this logic to a shared base class.

### CODE REVIEW

**Comment by jbischof** [comment]
Compared to #998 is there any difference here? Should this be the PR to move this functionality to the base classes? Or are we punting to be done in time for release?

**Comment by mattdangerw** [comment]
> Compared to https://github.com/keras-team/keras-nlp/pull/998 is there any difference here? Should this be the PR to move this functionality to the base classes? Or are we punting to be done in time for release?

Base class, I was thinking to punt on till post release yeah. A fast follow up. Some interesting question on how much we pull into the base class. Especially with seq2seq coming. So this is just 1-1 with the other PR for OPT for now.

**Review by jbischof — APPROVED** [review]
Thanks!

**Pull request merged**
