### PR TITLE
Replicate #536 changing GPT2 -> GPT2Backbone

### PR DESCRIPTION
**Pull request by ADITYADAS1999**
Replicate #536 changing GPT2 -> GPT2Backbone #539

1. gpt2_models.py -> gpt2_backbone.py
2. gpt2_models_test.py -> gpt2_backbone_test.py
3. GPT2 -> GPT2Backbone

### CODE REVIEW

**Comment by mattdangerw** [comment]
Thanks for the PR! I think the filenames should be all set already, no need to change them!

We just need to rename the `GPT2` symbol to `GPT2Backbone` wherever it is used. Thanks!

**Comment by ADITYADAS1999** [comment]
> Thanks for the PR! I think the filenames should be all set already, no need to change them!
> 
> We just need to rename the `GPT2` symbol to `GPT2Backbone` wherever it is used. Thanks!

Thanks for the information [mattdangerw](https://github.com/mattdangerw) . Can you give some hints which GPT2 symbol ? Or these are the classes?

**Comment by mattdangerw** [comment]
Sure! The remaining work here is to rename this symbol at this line to BertBackbone https://github.com/keras-team/keras-nlp/blob/a84770b84e3e0d9654fffe38d22dd24efe26f31e/keras_nlp/models/gpt2/gpt2_backbone.py#L35

And update all usages of the symbol

**Comment by ADITYADAS1999** [comment]
> Looking good @ADITYADAS1999 but remember to update the docstrings, e.g., [here](https://github.com/keras-team/keras-nlp/blob/a84770b84e3e0d9654fffe38d22dd24efe26f31e/keras_nlp/models/gpt2/gpt2_backbone.py#L77).

sure, 😃

**Review by mattdangerw — APPROVED** [review]
Thanks very much!

**Comment by ADITYADAS1999** [comment]
> Thanks very much!

awesome. you are very super active [mattdangerw](https://github.com/mattdangerw) 🙂

**Pull request merged**
