### PR TITLE
Fix gpt2, t5 and fnet under mixed precision

### PR DESCRIPTION
**Pull request by mattdangerw**
Also add a testing mode,  `--mixed_precision` for this, though it does not fully pass yet due to saving and other output errors.

### CODE REVIEW

**Comment by chenmoneygithub** [comment]
@mattdangerw I am very confused about the GCP testing failure, it complains about the diff between model outputs and loaded model outputs:
```
Step #5 - "create-job": E       not close lhs = [-0.02194774  0.03975677  0.0241155   0.02628191 -0.01379672 -0.01609562
Step #5 - "create-job": E         0.00820724 -0.02046685  0.02078998  0.01787513]
Step #5 - "create-job": E       not close rhs = [ 0.02194796 -0.03975716 -0.02411573 -0.02628217  0.01379685  0.01609577
Step #5 - "create-job": E        -0.00820732  0.02046705 -0.02079018 -0.0178753 ]
Step #5 - "create-job": E       not close dif = [0.0438957  0.07951393 0.04823123 0.05256408 0.02759357 0.03219139
Step #5 - "create-job": E        0.01641455 0.0409339  0.04158016 0.03575043]
Step #5 - "create-job": E       not close tol = [0.01021948 0.01039757 0.01024116 0.01026282 0.01013797 0.01016096
Step #5 - "create-job": E        0.01008207 0.01020467 0.0102079  0.01017875]
```

**Comment by mattdangerw** [comment]
@chenmoneygithub this is a recent and unrelated flake I believe. Happened on https://github.com/keras-team/keras-nlp/pull/856 as well.

**Review by chenmoneygithub — APPROVED** [review]

**Pull request merged**
