### PR TITLE
Run workflows with read-only tokens

### PR DESCRIPTION
**Pull request by pnacht**
Fixes https://github.com/keras-team/keras-nlp/issues/1304.

This PR ensures all KerasNLP workflows run with read-only tokens, protecting the project from supply-chain risks.

### CODE REVIEW

**Review by mattdangerw — APPROVED** [review]
This looks good to me! Let us know if you think we should merge this along with the setting change in https://github.com/keras-team/keras-nlp/issues/1304. That seems good, as as these workflow will never need write whatever our setting our, but I will wait for you to weigh in.

**Comment by pnacht** [comment]
Yeah, the repo setting ensures the default is secure, but this gives you an added layer of security in case someone accidentally changes the setting back (which happens more often than you'd think, since many third-party Actions simply suggest setting write-all instead of figuring out which permissions they actually need).

It also has the slight benefit of helping security tools such as the [OpenSSF Scorecard](https://github.com/ossf/scorecard) know the workflow is secure.

**Comment by mattdangerw** [comment]
Thank you!!

**Pull request merged**
