### PR TITLE
Pass Correct LayerNorm Epsilon value to TransformerEncoder in Backbones

### LINKED ISSUE #728: Incorrect `epsilon` (LayerNorm) for the Transformer Layer in All Backbones
Similar to https://github.com/keras-team/keras-nlp/issues/642. Please check whether the correct epsilon value has been passed. Do this for all backbones.

### PR DESCRIPTION
**Pull request by TheAthleticCoder**
Resolves #728

### CODE REVIEW

**Comment by abheesht17** [comment]
LGTM!

**Comment by TheAthleticCoder** [comment]
@mattdangerw A gentle reminder regarding the commit

**Comment by mattdangerw** [comment]
@TheAthleticCoder thanks! This looks good, but would it be possible to drop a comment here with links to where you found these constants? Would be a useful reference anyway.

**Comment by TheAthleticCoder** [comment]
@mattdangerw The values of the constants were already there in the model files (model_backbone.py). I used those pre-existing constants and passed them into the main model architecture.

**Comment by mattdangerw** [comment]
Ah got it! Thank you.

**Pull request merged**
