### PR TITLE
update input_image_shape -> image_shape

### PR DESCRIPTION
**Pull request by divyashreepathihalli**

### CODE REVIEW

**Comment by mattdangerw** [comment]
Looks like a legit test failure to dig into!

**Comment by divyashreepathihalli** [comment]
> Looks like a legit test failure to dig into!

oh wow! just a rename and all these error! so weird!

**Comment by mattdangerw** [comment]
Still see the resnet failures. Might be because you are missing this one https://github.com/keras-team/keras-nlp/blob/keras-hub/keras_nlp/src/tests/test_case.py#L504-L508

**Review by mattdangerw — APPROVED** [review]
Lgtm

**Pull request merged**
