### PR TITLE
Update model and file names for DistilBert

### LINKED ISSUE #510: Update model and file names for DistilBert
Given our new [naming guidelines](https://github.com/keras-team/keras-nlp/blob/master/STYLE_GUIDE.md#naming-of-layers-and-models), "distil" and "bert" are both segments in the DistilBert class name. This means the filenames and preset ids should look like `distil_bert_xx.py` and `distil_bert_base_xx`. Current we have `distilbert_xx.py`.

This would also be more consistent with XMLRoberta. E.g. `distil_bert` and `xlm_roberta`.

### PR DESCRIPTION
**Pull request by ADITYADAS1999**
Update model and file names for DistilBert. Closes #510

Given our new [naming guidelines](https://github.com/keras-team/keras-nlp/blob/master/STYLE_GUIDE.md#naming-of-layers-and-models), "distil" and "bert" are both segments in the DistilBert class name. This means the filenames and preset ids should look like distil_bert_xx.py and distil_bert_base_xx. Current we have distilbert_xx.py.

This would also be more consistent with XMLRoberta. E.g. distil_bert and xlm_roberta.

### CODE REVIEW

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999 I didn't realize that the tests had not been run. Shouldn't we need to change the imports, e.g., [here](https://github.com/keras-team/keras-nlp/blob/3a97ed537adfe26c1c9bdc33ebeea8da193168f6/keras_nlp/models/distilbert/distilbert_models_test.py#L22)?

sry for confusing, I changes this

**Comment by ADITYADAS1999** [comment]
> Remember to this the `__init__.py` file in the base on the `models` directory, and the `tools/checkpoints_conversion` directory too. Thanks very much for contributing!!

thanks for informing.

**Comment by ADITYADAS1999** [comment]
> Thanks for the PR @ADITYADAS1999! LGTM, but make sure sign our CLA so I can merge!

cli

which option I can choose for sign the CLA ?

**Comment by jbischof** [comment]
@ADITYADAS1999 if you are a student you should choose "only yourself". 

As a side note, if you are employed make sure to talk to your employer first as many contracts make copyright claims on employee work.

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999 if you are a student you should choose "only yourself".
> 
> As a side note, if you are employed make sure to talk to your employer first as many contracts make copyright claims on employee work.

Thank for helping @jbischof 😊

**Comment by jbischof** [comment]
Great start @ADITYADAS1999! I suggest you run `pytest keras_nlp/models` to quickly find the rest of the symbols to update. Most of the files will need some change in the imports.

**Review by jbischof — APPROVED** [review]
Great work @ADITYADAS1999! Welcome to the keras-nlp team!

**Comment by ADITYADAS1999** [comment]
> Great work @ADITYADAS1999! Welcome to the keras-nlp team!

Thanks 🤓 @jbischof  , I love to contribute projects. Now Let's do it. 🧑‍💻

**Pull request merged**
