### PR TITLE
Replace requests with keras.utils.get_file

### PR DESCRIPTION
**Pull request by soma2000-lang**
Resolves https://github.com/keras-team/keras-nlp/issues/864 @abheesht17

### CODE REVIEW

**Review by abheesht17 — CHANGES_REQUESTED** [review]
Have just had a cursory look and it seems that merely replacing "requests.get" with "keras.utils.get_file" might not work as intended! Please go through the documentation and make the appropriate changes: https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file. Thanks!

**Comment by abheesht17** [comment]
@soma2000-lang, any updates here? If you are stuck somewhere, we can help you out!

**Comment by soma2000-lang** [comment]
@soma2000-lang Sure I will ask ,but I have a query at #756 .Can you please help me out there

**Comment by soma2000-lang** [comment]
@abheesht17 mind checking it once.Thanks!

**Comment by abheesht17** [comment]
@soma2000-lang, will review this, but have you tried running the script once?

**Comment by soma2000-lang** [comment]
Yes @abheesht17 
image

**Comment by soma2000-lang** [comment]
@abheesht17  Can you help me here.

**Pull request closed without merging**
