### PR TITLE
Fix/allow different encoder and decoder feature dimensions in transformer decoder layer

### PR DESCRIPTION
**Pull request by ferraric**
Fixes https://github.com/keras-team/keras-nlp/issues/1235

Thanks @fdtomasi for the detailed issue report, made fixing this quite easy.

### CODE REVIEW

**Review by mattdangerw — APPROVED** [review]
Awesome! Looks good to me, thanks for the change

**Comment by ferraric** [comment]
> Awesome! Looks good to me, thanks for the change

You're welcome! Any idea when this might make it into a release?

**Comment by mattdangerw** [comment]
> You're welcome! Any idea when this might make it into a release?

Good question! The next big release will probably be timed along with the initial Keras 3 pip. That's this year, but might not be the month.

But we can and should cut a small point release in the next couple weeks if the big release is going to drag on a bit.

**Comment by ferraric** [comment]
> > You're welcome! Any idea when this might make it into a release?
> 
> Good question! The next big release will probably be timed along with the initial Keras 3 pip. That's this year, but might not be the month.
> 
> But we can and should cut a small point release in the next couple weeks if the big release is going to drag on a bit.

Thanks for the info. A release soon would be appreciated since I am waiting on this feature. Of course only if possible and not too much overhead.

**Pull request merged**
