### PR TITLE
Extend the timeout for large tests

### PR DESCRIPTION
**Pull request by mattdangerw**
We are getting more models and with tensorflow 2.12 also check the new saved model format.

We should think of where to save time on tests, but for now can do the easy fix.

### CODE REVIEW

**Comment by jbischof** [comment]
You might want to consider something like https://github.com/keras-team/keras-cv/pull/1898 instead to keep our test size under control.

**Comment by mattdangerw** [comment]
sure I am down!

**Comment by mattdangerw** [comment]
We might still want this, even with https://github.com/keras-team/keras-nlp/pull/1104, test run still took over 50 minutes.

Unlike KerasCV our models are larger, and we had already sped up our tf saving test by turning off all tracing/compilation https://github.com/keras-team/keras-nlp/pull/945, so I think the change has less of an overall inpact.

**Comment by mattdangerw** [comment]
let's close this for now as we are about to majorly change our GCP runs to support GPU on jax, tf and torch

can revisit after

**Review by jbischof — APPROVED** [review]

**Comment by ianstenbit** [comment]
BTW I noticed the TPU GCB isn't running at all -- is that meant to be deleted or are we just waiting to enable it?

**Comment by mattdangerw** [comment]
> BTW I noticed the TPU GCB isn't running at all -- is that meant to be deleted or are we just waiting to enable it?

Just some work that needs to get prioritized at some point. We landed some TPU testing, but in a super incomplete state, and never enabled persistent CI for it.

**Pull request merged**
