### PR TITLE
Mark format.sh executable again

### PR DESCRIPTION
**Pull request by mattdangerw**
We appear to have lost the executable bit.

### CODE REVIEW

**Review by jbischof — APPROVED** [review]

**Review by chenmoneygithub — COMMENTED** [review]
The change seems to be empty?

**Comment by jbischof** [comment]
I think this is just the old `chmod +x`.

**Comment by jbischof** [comment]
Now that I say it out loud, maybe I am also confused. Isn't file permission a local setting? How would this affect the repo?

**Comment by mattdangerw** [comment]
Git actually tracks file permissions! At least it specifically tracks an executable bit.

If you navigate to https://github.com/keras-team/keras-nlp/blob/master/shell/lint.sh is actually marked "Executable File" when you click on it. That's not true for `format.sh`, though we dropped it a recent PR, we used to have the permission set for it as well.

**Review by chenmoneygithub — APPROVED** [review]

**Pull request merged**
