### PR TITLE
Make version number SSoT.

### PR DESCRIPTION
**Pull request by fchollet**
Avoiding redundancy in specifying the version number. Added benefit: it prevents folks from incorrectly using `setup.py` and points them towards the correct workflow.

### CODE REVIEW

**Comment by mattdangerw** [comment]
We might want to wait until we are ready to update a few things here. This will break the contributor guide, a lot of colabs, and the "run for source" instructions on this README and keras.io right?

Can take a look next week probably.

**Comment by fchollet** [comment]
Sounds good, let's wait.

**Pull request merged**
