### PR TITLE
Start landing code for Kaggle integration

### PR DESCRIPTION
**Pull request by mattdangerw**
Ready for review. We are going to land this on a feature branch while we ready our kaggle assets.

See file contents here:
https://colab.sandbox.google.com/gist/mattdangerw/5cd52f8a2aa9517b92cc26d15a92a73d/preset-directories.ipynb

Follow ups:
- Switch all preprocessing layers to the deferred "packer" creation to account for `load_assets` happening after `__init__`.
- Port other tokenizer to `save_assets`/`load_assets`.
- Put the right metadata in our metadata.json.
- Unit tests for preset_utils.

### CODE REVIEW

**Comment by fchollet** [comment]
Everything looks good. Possible alternatives to `tokenizer_assets/vocabulary.txt` we might consider (since the tokenizer is special-cased anyway):

- `assets/tokenizer/vocabulary.txt` (IMO this is what makes the most sense)
- `tokenizer/tokenizer.json` + `tokenizer/vocabulary.txt`
- Just top level `vocabulary.txt` (probably not ideal)

**Comment by mattdangerw** [comment]
I like the first or third option.

First gives us room to grow with more special cased asset dir names where every layer owns a dir. Third prioritizes online browsing UX over everything.

Let's go with the first option for now. That seems like the consensus pick.

**Comment by fchollet** [comment]
Sounds good!

**Pull request merged**
