### PR TITLE
Test against Keras 3

### PR DESCRIPTION
**Pull request by mattdangerw**

### CODE REVIEW

**Comment by mattdangerw** [comment]
Sounds like this will actually need to wait another for another nightly or two before we can push this.

**Comment by mattdangerw** [comment]
OK this should be finally ready for review. I am disabling compilation for torch for now, though that is probably a decision we should reverse before a release. I am seeing a number of failures when attempting to compile on torch.

**Review by divyashreepathihalli — APPROVED** [review]

**Comment by mattdangerw** [comment]
Filed https://github.com/keras-team/keras-nlp/issues/1296 for the flake here. Pulling this in.

**Pull request merged**
