### PR TITLE
add vicuna preset

### PR DESCRIPTION
**Pull request by sineeli**

### CODE REVIEW

**Comment by sineeli** [comment]
cc: @mattdangerw

**Comment by mattdangerw** [comment]
Thank you! Trying it out now.

**Comment by mattdangerw** [comment]
Thanks! This looks good. I was having trouble loading this, but then remembered that since this is under the llama community license, you will actually have to be logged in to kaggle to download the assets.

**Comment by mattdangerw** [comment]
Will pull this in. Is there a specific prompt structure for vicuna?

**Comment by sineeli** [comment]
@mattdangerw,

sorry for the delayed response I didn't see the comment.

As per official [repo](https://github.com/lm-sys/FastChat) I don't see any specific prompt.

**Pull request merged**
