### PR TITLE
Add API exports for layers documented on keras.io

### PR DESCRIPTION
**Pull request by fchollet**

### CODE REVIEW

**Comment by mattdangerw** [comment]
We should actually just do the full list here I think! Preprocessing and trainable layers.

https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/layers/__init__.py#L15-L31

**Review by mattdangerw — CHANGES_REQUESTED** [review]
Still missing TransformerEncoder I think!

Also worth noting these are all documented, we just currently list them in two places
https://keras.io/api/keras_nlp/modeling_layers/
https://keras.io/api/keras_nlp/preprocessing_layers/
(happy to change that, no strong feelings)

**Comment by fchollet** [comment]
> Still missing TransformerEncoder I think!

That one was part of the original PR. It's already covered.

**Review by mattdangerw — APPROVED** [review]
Hah whoops! LGTM

**Pull request merged**
